---
- name: User
  user:
    name: '{{ buildbot_master_user }}'
    comment: 'Dedicated user to run the buildbot master'
    shell: '/bin/bash'

- name: Create Master
  command: 'buildbot create-master {{ buildbot_master_basedir }}'
  become: true
  become_user: '{{ buildbot_master_user }}'
  args:
    creates: '{{ buildbot_master_basedir }}/buildbot.tac'
  register: buildbot_master_create_result
  notify:
  - restart buildbot master

- name: Upgrade Master
  command: 'buildbot upgrade-master {{ buildbot_master_basedir }}'
  become: true
  become_user: '{{ buildbot_master_user }}'
  when: >
    ((buildbot_master_pip_result | default({})).changed | default(False))
    and not buildbot_master_create_result.changed
  notify:
  - restart buildbot master

- name: store facts
  set_fact:
    buildbot_master_basedir: '{{ buildbot_master_basedir }}'
    buildbot_master_user: '{{ buildbot_master_user }}'
  tags: [always]
