---
- name: install APT packages
  apt:
    name: "{{ buildbot_master_apt_packages }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400

- name: update PIP/Setuptools
  pip:
    name:
      - pip
      - setuptools
    state: latest
    executable: pip3
  # if this fails try:
  #   python3 -m pip install --upgrade pip

- name: Install PIP packages
  pip:
    name: "{{ buildbot_master_pip_packages }}"
    executable: pip3
    extra_args: "--ignore-installed PyYAML"

- name: Install PIP buildbot
  pip:
    name:
      - buildbot[tls] # explicitly set the TLS option
      - buildbot-www
      - buildbot-waterfall-view
      - buildbot-console-view
    version: "{{ buildbot_version }}"
    executable: pip3
  notify:
  - restart buildbot masters

- name: SystemD Unit File
  template:
    src: buildbot.service.j2
    dest: /etc/systemd/system/buildbot.service

- name: Path
  file:
    path: "{{ buildbot_master_path }}"
    state: directory

- name: Store Facts
  set_fact:
    buildbot_master_path: '{{ buildbot_master_path }}'
  tags: [always]
